var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/ai/generate-local/route.js")
R.c("server/chunks/[root-of-the-server]__e7e31c36._.js")
R.c("server/chunks/src_lib_auth_ts_f5ef5b5b._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_3712ea0b.js")
R.c("server/chunks/node_modules_next_0700e68e._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_5060e774._.js")
R.c("server/chunks/_next-internal_server_app_api_ai_generate-local_route_actions_01a2ddbe.js")
R.m(730956)
module.exports=R.m(730956).exports
