var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__f62d412e._.js")
R.c("server/chunks/ssr/_a3b9117b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_8a37abed._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1f510447._.js")
R.c("server/chunks/ssr/node_modules_423e7141._.js")
R.c("server/chunks/ssr/node_modules_next_dist_982e7503._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/_next-internal_server_app__global-error_page_actions_75761787.js")
R.m(461837)
module.exports=R.m(461837).exports
