var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/feedback/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__87e125ef._.js")
R.c("server/chunks/ssr/_a3b9117b._.js")
R.c("server/chunks/ssr/_f8ee9f62._.js")
R.c("server/chunks/ssr/[root-of-the-server]__c99a8634._.js")
R.c("server/chunks/ssr/node_modules_423e7141._.js")
R.c("server/chunks/ssr/node_modules_next_dist_982e7503._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_a83c72f6._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_feedback_page_actions_ad090f73.js")
R.m(270954)
module.exports=R.m(270954).exports
