// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/broadcast/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/broadcast">> = Specific
  const handler = {} as typeof import("../../src/app/admin/broadcast/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/data/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/data">> = Specific
  const handler = {} as typeof import("../../src/app/admin/data/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/features/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/features">> = Specific
  const handler = {} as typeof import("../../src/app/admin/features/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/prompts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/prompts">> = Specific
  const handler = {} as typeof import("../../src/app/admin/prompts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/skills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/skills">> = Specific
  const handler = {} as typeof import("../../src/app/admin/skills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/store/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/store">> = Specific
  const handler = {} as typeof import("../../src/app/admin/store/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/store/publish/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/store/publish">> = Specific
  const handler = {} as typeof import("../../src/app/admin/store/publish/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/sync/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sync">> = Specific
  const handler = {} as typeof import("../../src/app/admin/sync/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/tickets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tickets">> = Specific
  const handler = {} as typeof import("../../src/app/admin/tickets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/transactions">> = Specific
  const handler = {} as typeof import("../../src/app/admin/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/airribbon/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/airribbon">> = Specific
  const handler = {} as typeof import("../../src/app/airribbon/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/qr-confirm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/qr-confirm">> = Specific
  const handler = {} as typeof import("../../src/app/auth/qr-confirm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/transactions">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../src/app/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/features/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features">> = Specific
  const handler = {} as typeof import("../../src/app/features/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/feedback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feedback">> = Specific
  const handler = {} as typeof import("../../src/app/feedback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mock/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mock">> = Specific
  const handler = {} as typeof import("../../src/app/mock/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/payment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payment">> = Specific
  const handler = {} as typeof import("../../src/app/payment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/promo/jntm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/promo/jntm">> = Specific
  const handler = {} as typeof import("../../src/app/promo/jntm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/store/mock/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/store/mock">> = Specific
  const handler = {} as typeof import("../../src/app/store/mock/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/store/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/store">> = Specific
  const handler = {} as typeof import("../../src/app/store/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support">> = Specific
  const handler = {} as typeof import("../../src/app/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/wordchatbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wordchatbox">> = Specific
  const handler = {} as typeof import("../../src/app/wordchatbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ai/generate-local/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/ai/generate-local">> = Specific
  const handler = {} as typeof import("../../src/app/ai/generate-local/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ai/get-key/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/ai/get-key">> = Specific
  const handler = {} as typeof import("../../src/app/ai/get-key/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/export-db/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/export-db">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/export-db/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/features/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/features">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/features/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/settings/upload-installer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/settings/upload-installer">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/settings/upload-installer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/skills/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/skills">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/skills/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/store/audit/aggregate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/store/audit/aggregate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/store/audit/aggregate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/store/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/store/audit">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/store/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/store/install-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/store/install-logs">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/store/install-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/store/migrate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/store/migrate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/store/migrate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/store/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/store/publish">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/store/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/store/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/store/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/store/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/tickets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tickets">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/tickets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/transactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/transactions">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/transactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/generate-local/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/generate-local">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/generate-local/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/get-config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/get-config">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/get-config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/get-key/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/get-key">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/get-key/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/alipay/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/alipay/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/alipay/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/alipay/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/alipay/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/alipay/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/alipay/dev/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/alipay/dev">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/alipay/dev/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/alipay/qrcode/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/alipay/qrcode">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/alipay/qrcode/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/alipay/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/alipay/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/alipay/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/qrcode/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/qrcode/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/qrcode/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/qrcode/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/qrcode">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/qrcode/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/qrcode/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/qrcode/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/qrcode/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/referral/[code]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/referral/[code]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/referral/[code]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/send-code/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/send-code">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/send-code/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/wechat/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/wechat/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/wechat/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/wechat/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/wechat/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/wechat/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/wechat/dev/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/wechat/dev">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/wechat/dev/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/wechat/qrcode/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/wechat/qrcode">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/wechat/qrcode/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/wechat/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/wechat/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/wechat/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/broadcast/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/broadcast">> = Specific
  const handler = {} as typeof import("../../src/app/api/broadcast/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/broadcast/sse/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/broadcast/sse">> = Specific
  const handler = {} as typeof import("../../src/app/api/broadcast/sse/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/feature-usage/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feature-usage/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/feature-usage/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/features/[id]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/features/[id]/comments">> = Specific
  const handler = {} as typeof import("../../src/app/api/features/[id]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/features/[id]/vote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/features/[id]/vote">> = Specific
  const handler = {} as typeof import("../../src/app/api/features/[id]/vote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/features/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/features">> = Specific
  const handler = {} as typeof import("../../src/app/api/features/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/latex/render/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/latex/render">> = Specific
  const handler = {} as typeof import("../../src/app/api/latex/render/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/locale/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locale">> = Specific
  const handler = {} as typeof import("../../src/app/api/locale/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/models/available/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/models/available">> = Specific
  const handler = {} as typeof import("../../src/app/api/models/available/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payment/create-order/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment/create-order">> = Specific
  const handler = {} as typeof import("../../src/app/api/payment/create-order/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payment/mock-pay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment/mock-pay">> = Specific
  const handler = {} as typeof import("../../src/app/api/payment/mock-pay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payment/qrcode/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment/qrcode">> = Specific
  const handler = {} as typeof import("../../src/app/api/payment/qrcode/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payment/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/payment/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payment/webhook/alipay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment/webhook/alipay">> = Specific
  const handler = {} as typeof import("../../src/app/api/payment/webhook/alipay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payment/webhook/wechat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment/webhook/wechat">> = Specific
  const handler = {} as typeof import("../../src/app/api/payment/webhook/wechat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/promo/buyback/apply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/promo/buyback/apply">> = Specific
  const handler = {} as typeof import("../../src/app/api/promo/buyback/apply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/promo/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/promo/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/promo/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/promo/transfer/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/promo/transfer/create">> = Specific
  const handler = {} as typeof import("../../src/app/api/promo/transfer/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/referral/[code]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/referral/[code]">> = Specific
  const handler = {} as typeof import("../../src/app/api/referral/[code]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/referral/apply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/referral/apply">> = Specific
  const handler = {} as typeof import("../../src/app/api/referral/apply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/referral/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/referral/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/referral/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/referral/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/referral/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/referral/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/referral/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/referral/validate">> = Specific
  const handler = {} as typeof import("../../src/app/api/referral/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/store/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/store/download">> = Specific
  const handler = {} as typeof import("../../src/app/api/store/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/store/install/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/store/install/report">> = Specific
  const handler = {} as typeof import("../../src/app/api/store/install/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/store/install/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/store/install">> = Specific
  const handler = {} as typeof import("../../src/app/api/store/install/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/store/license/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/store/license/verify">> = Specific
  const handler = {} as typeof import("../../src/app/api/store/license/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/store/licenses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/store/licenses">> = Specific
  const handler = {} as typeof import("../../src/app/api/store/licenses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/store/pay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/store/pay">> = Specific
  const handler = {} as typeof import("../../src/app/api/store/pay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/store/plugins/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/store/plugins">> = Specific
  const handler = {} as typeof import("../../src/app/api/store/plugins/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/store/receipt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/store/receipt">> = Specific
  const handler = {} as typeof import("../../src/app/api/store/receipt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/store/redownload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/store/redownload">> = Specific
  const handler = {} as typeof import("../../src/app/api/store/redownload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/store/releases/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/store/releases">> = Specific
  const handler = {} as typeof import("../../src/app/api/store/releases/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/store/skills/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/store/skills">> = Specific
  const handler = {} as typeof import("../../src/app/api/store/skills/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/store/update/check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/store/update/check">> = Specific
  const handler = {} as typeof import("../../src/app/api/store/update/check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/store/update/package/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/store/update/package">> = Specific
  const handler = {} as typeof import("../../src/app/api/store/update/package/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/store/update/rollback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/store/update/rollback">> = Specific
  const handler = {} as typeof import("../../src/app/api/store/update/rollback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscription/config/[configId]/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscription/config/[configId]/download">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscription/config/[configId]/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscription/config/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscription/config/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscription/config/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sync/user-profile/ack/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync/user-profile/ack">> = Specific
  const handler = {} as typeof import("../../src/app/api/sync/user-profile/ack/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sync/user-profile/pull/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync/user-profile/pull">> = Specific
  const handler = {} as typeof import("../../src/app/api/sync/user-profile/pull/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/system-users/complete-profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/system-users/complete-profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/system-users/complete-profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/system-users/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/system-users/metrics">> = Specific
  const handler = {} as typeof import("../../src/app/api/system-users/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tickets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tickets">> = Specific
  const handler = {} as typeof import("../../src/app/api/tickets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tokens/add/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tokens/add">> = Specific
  const handler = {} as typeof import("../../src/app/api/tokens/add/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tokens/balance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tokens/balance">> = Specific
  const handler = {} as typeof import("../../src/app/api/tokens/balance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tokens/credit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tokens/credit">> = Specific
  const handler = {} as typeof import("../../src/app/api/tokens/credit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tokens/deduct/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tokens/deduct">> = Specific
  const handler = {} as typeof import("../../src/app/api/tokens/deduct/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tokens/income/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tokens/income">> = Specific
  const handler = {} as typeof import("../../src/app/api/tokens/income/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tokens/local-ad-views/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tokens/local-ad-views">> = Specific
  const handler = {} as typeof import("../../src/app/api/tokens/local-ad-views/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tokens/sync-ad-views/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tokens/sync-ad-views">> = Specific
  const handler = {} as typeof import("../../src/app/api/tokens/sync-ad-views/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tokens/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tokens/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/tokens/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/transactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/transactions">> = Specific
  const handler = {} as typeof import("../../src/app/api/transactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/usage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/usage">> = Specific
  const handler = {} as typeof import("../../src/app/api/usage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/features/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/features">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/features/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/usage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/usage">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/usage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/xai/check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/xai/check">> = Specific
  const handler = {} as typeof import("../../src/app/api/xai/check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tokens/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/tokens/sync">> = Specific
  const handler = {} as typeof import("../../src/app/tokens/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
